/* eslint no-console: 0 */
const fs = require('fs');
const path = require('path');
const { compile, JSONSchema } = require('json-schema-to-typescript');
const { SchemaValidator } = require('./schemaValidator');
const { getSchemaNames, schemaDirectory } = require('./getSchemaNames');

// The directory where the resulting data.d.ts file will be saved
const outputPath = path.join(__dirname, '..', '..', 'types');
const bannerComment =
  "/* tslint:disable */\n/**\n* This file was automatically generated by json-schema-to-typescript.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n* and run 'yarn generate-typescript' to regenerate this file.\n*/\n\n";

const schemaNames = getSchemaNames();

const promises = schemaNames.map(generateTypeScriptFromSchema);

Promise.all(promises).then((result) => {
  saveFile(result.join('\n'));
});

/**
 * Loads the given schema by name and generates typescript interfaces from it.
 *
 * @param schemaName the given schema name
 * @returns A Promise that will resolve to the generated typescript
 */
function generateTypeScriptFromSchema(schemaName: string) {
  const validator = new SchemaValidator(path.join(__dirname, schemaDirectory));

  // Sets the current working directory (cwd) to the schema directory, in order
  // for the typescript generator to properly resolve external references
  const generateOptions = {
    cwd: path.join(__dirname, schemaDirectory, schemaName),
    ignoreMinAndMaxItems: true,
    bannerComment: '',
  };

  return validator.init().then((validate) => {
    return compile(
      validate.schema as JSONSchema,
      schemaName,
      generateOptions
    ).then((ts) => {
      console.info(`Generated typescript for schema '${schemaName}'`);
      return ts;
    });
  });
}

function saveFile(typescriptSources: string) {
  const outputFile = path.join(outputPath, 'data.d.ts');
  fs.writeFileSync(outputFile, `${bannerComment}${typescriptSources}`, {
    encoding: 'utf8',
  });
  console.info(`Written typescript output to file '${outputFile}'`);
}
