export type IconName =
  | 'AfstandSporten'
  | 'AlcoholVerkoop'
  | 'Archive'
  | 'Arrow'
  | 'ArrowWithIntensity'
  | 'Arts'
  | 'Avondklok'
  | 'BarChart'
  | 'BasisregelsAfstand'
  | 'BasisregelsDrukte'
  | 'BasisregelsElleboog'
  | 'BasisregelsGeenBezoek'
  | 'BasisregelsHandenwassen'
  | 'BasisregelsMondkapje'
  | 'BasisregelsTesten'
  | 'Bevolking'
  | 'Bezoek'
  | 'Bibliotheek'
  | 'BinnenMetZitplaats'
  | 'BinnenZonderZitplaats'
  | 'Binnensporten'
  | 'Binnensportlocaties'
  | 'Boosterprik'
  | 'Calendar'
  | 'CalendarGear'
  | 'Check'
  | 'Checked'
  | 'ChevronDown'
  | 'ChevronRight'
  | 'Clock'
  | 'Close'
  | 'CloseThick'
  | 'ContactBeroepen'
  | 'Coronathermometer'
  | 'Coronavirus'
  | 'Cross'
  | 'Database'
  | 'DoorstroomEvenementen'
  | 'Dot'
  | 'Down'
  | 'Download'
  | 'EenPersoonDoorgestreept'
  | 'Elderly'
  | 'ElderlyPeople'
  | 'Expand'
  | 'Experimenteel'
  | 'External'
  | 'Eye'
  | 'FrisseLucht'
  | 'GedeeltelijkOpenRugzak'
  | 'GeenEntertainment'
  | 'GeenMaxAantalBezoekers'
  | 'GeenWedstrijden'
  | 'Gehandicaptenzorg'
  | 'GeorganiseerdeKunstEnCultuurbeoefening'
  | 'GgdTesten'
  | 'Groepen'
  | 'HealthCare'
  | 'Home'
  | 'HomeAndVisits'
  | 'HorecaEnEvenementenBestellen'
  | 'HorecaEnEvenementenEtendrinken'
  | 'HorecaEnEvenementenEvenementen'
  | 'HorecaEvenementen'
  | 'Hospitality'
  | 'Information'
  | 'IntensiveCareOpnames'
  | 'Klachten'
  | 'Klok210001'
  | 'KunstCultuur'
  | 'KunstcultuurMusea'
  | 'Line'
  | 'Locaties'
  | 'Location'
  | 'Lopend'
  | 'Maatregelen'
  | 'MaxAantalBezoekers'
  | 'MaxVisitors'
  | 'MedischeScreening'
  | 'MeerInformatie'
  | 'MeerdaagseEvenementen'
  | 'Menu'
  | 'Mondkapje'
  | 'Nederland'
  | 'Notification'
  | 'OnderwijsEnKinderopvangNoodopvang'
  | 'OnderwijsEnKinderopvangOpAfstand'
  | 'OntmoetingenBezoek'
  | 'OpenbaarVervoer'
  | 'Openingstijden'
  | 'Other'
  | 'Overige'
  | 'Phone'
  | 'Recreatie'
  | 'Reizen'
  | 'ReproductieGraf'
  | 'Reproductiegetal'
  | 'Rioolvirus'
  | 'SearchIcon'
  | 'SearchIconBold'
  | 'SportBuiten'
  | 'SportMetZweetband'
  | 'SportWedstrijden'
  | 'Stap1HorecaMax'
  | 'Stap1HorecaPertafel'
  | 'Stap1HorecaVerplaatsen'
  | 'Stap1OnderwijsBibliotheek'
  | 'Stap1OnderwijsOpen'
  | 'Stap1Theorie'
  | 'Stap1Thuisbezoek'
  | 'Stap1Uitvaarten'
  | 'Stap1WinkelsAlleen'
  | 'Stap1WinkelsMarkten'
  | 'Stap1WinkelsOpen'
  | 'Stopwatch'
  | 'Taxi'
  | 'Testbewijs'
  | 'Toegangsbewijzen'
  | 'Town'
  | 'Travel'
  | 'Unchecked'
  | 'Up'
  | 'Vaccinaties'
  | 'Varianten'
  | 'Verpleeghuis'
  | 'VervoerEnReizenBuitenland'
  | 'VervoerEnReizenOv'
  | 'Vliegen'
  | 'VulnerableGroups'
  | 'Warn'
  | 'Warning'
  | 'WinkelenEnBoodschappenAlcohol'
  | 'WinkelenEnBoodschappenOpen'
  | 'Work'
  | 'Ziekenhuis'
  | 'Ziektegolf';

export const iconName2filename: Record<IconName, string> = {
  AfstandSporten: 'afstand_sporten.svg',
  AlcoholVerkoop: 'alcohol_verkoop.svg',
  Archive: 'archive.svg',
  Arrow: 'arrow.svg',
  ArrowWithIntensity: 'arrow_with_intensity.svg',
  Arts: 'arts.svg',
  Avondklok: 'avondklok.svg',
  BarChart: 'bar_chart.svg',
  BasisregelsAfstand: 'basisregels_afstand.svg',
  BasisregelsDrukte: 'basisregels_drukte.svg',
  BasisregelsElleboog: 'basisregels_elleboog.svg',
  BasisregelsGeenBezoek: 'basisregels_geen_bezoek.svg',
  BasisregelsHandenwassen: 'basisregels_handenwassen.svg',
  BasisregelsMondkapje: 'basisregels_mondkapje.svg',
  BasisregelsTesten: 'basisregels_testen.svg',
  Bevolking: 'bevolking.svg',
  Bezoek: 'bezoek.svg',
  Bibliotheek: 'bibliotheek.svg',
  BinnenMetZitplaats: 'binnen_met_zitplaats.svg',
  BinnenZonderZitplaats: 'binnen_zonder_zitplaats.svg',
  Binnensporten: 'binnensporten.svg',
  Binnensportlocaties: 'binnensportlocaties.svg',
  Boosterprik: 'boosterprik.svg',
  Calendar: 'calendar.svg',
  CalendarGear: 'calendar_gear.svg',
  Check: 'check.svg',
  Checked: 'checked.svg',
  ChevronDown: 'chevron_down.svg',
  ChevronRight: 'chevron_right.svg',
  Clock: 'clock.svg',
  Close: 'close.svg',
  CloseThick: 'close_thick.svg',
  ContactBeroepen: 'contact_beroepen.svg',
  Coronathermometer: 'coronathermometer.svg',
  Coronavirus: 'coronavirus.svg',
  Cross: 'cross.svg',
  Database: 'database.svg',
  DoorstroomEvenementen: 'doorstroom_evenementen.svg',
  Dot: 'dot.svg',
  Down: 'down.svg',
  Download: 'download.svg',
  EenPersoonDoorgestreept: 'een_persoon_doorgestreept.svg',
  Elderly: 'elderly.svg',
  ElderlyPeople: 'elderly-people.svg',
  Expand: 'expand.svg',
  Experimenteel: 'experimenteel.svg',
  External: 'external.svg',
  Eye: 'eye.svg',
  FrisseLucht: 'frisse_lucht.svg',
  GedeeltelijkOpenRugzak: 'gedeeltelijk_open_rugzak.svg',
  GeenEntertainment: 'geen_entertainment.svg',
  GeenMaxAantalBezoekers: 'geen_max_aantal_bezoekers.svg',
  GeenWedstrijden: 'geen_wedstrijden.svg',
  Gehandicaptenzorg: 'gehandicaptenzorg.svg',
  GeorganiseerdeKunstEnCultuurbeoefening:
    'georganiseerde_kunst_en_cultuurbeoefening.svg',
  GgdTesten: 'ggd_testen.svg',
  Groepen: 'groepen.svg',
  HealthCare: 'health_care.svg',
  Home: 'home.svg',
  HomeAndVisits: 'home_and_visits.svg',
  HorecaEnEvenementenBestellen: 'horeca_en_evenementen_bestellen.svg',
  HorecaEnEvenementenEtendrinken: 'horeca_en_evenementen_etendrinken.svg',
  HorecaEnEvenementenEvenementen: 'horeca_en_evenementen_evenementen.svg',
  HorecaEvenementen: 'horeca_evenementen.svg',
  Hospitality: 'hospitality.svg',
  Information: 'information.svg',
  IntensiveCareOpnames: 'intensive_care_opnames.svg',
  Klachten: 'klachten.svg',
  Klok210001: 'klok_2100-01.svg',
  KunstCultuur: 'kunst_cultuur.svg',
  KunstcultuurMusea: 'kunstcultuur_musea.svg',
  Line: 'line.svg',
  Locaties: 'locaties.svg',
  Location: 'location.svg',
  Lopend: 'lopend.svg',
  Maatregelen: 'maatregelen.svg',
  MaxAantalBezoekers: 'max_aantal_bezoekers.svg',
  MaxVisitors: 'max_visitors.svg',
  MedischeScreening: 'medische_screening.svg',
  MeerInformatie: 'meer_informatie.svg',
  MeerdaagseEvenementen: 'meerdaagse_evenementen.svg',
  Menu: 'menu.svg',
  Mondkapje: 'mondkapje.svg',
  Nederland: 'nederland.svg',
  Notification: 'notification.svg',
  OnderwijsEnKinderopvangNoodopvang: 'onderwijs_en_kinderopvang_noodopvang.svg',
  OnderwijsEnKinderopvangOpAfstand: 'onderwijs_en_kinderopvang_op_afstand.svg',
  OntmoetingenBezoek: 'ontmoetingen_bezoek.svg',
  OpenbaarVervoer: 'openbaar_vervoer.svg',
  Openingstijden: 'openingstijden.svg',
  Other: 'other.svg',
  Overige: 'overige.svg',
  Phone: 'phone.svg',
  Recreatie: 'recreatie.svg',
  Reizen: 'reizen.svg',
  ReproductieGraf: 'reproductie_graf.svg',
  Reproductiegetal: 'reproductiegetal.svg',
  Rioolvirus: 'rioolvirus.svg',
  SearchIcon: 'search-icon.svg',
  SearchIconBold: 'search_icon_bold.svg',
  SportBuiten: 'sport_buiten.svg',
  SportMetZweetband: 'sport_met_zweetband.svg',
  SportWedstrijden: 'sport_wedstrijden.svg',
  Stap1HorecaMax: 'stap_1_horeca_max.svg',
  Stap1HorecaPertafel: 'stap_1_horeca_pertafel.svg',
  Stap1HorecaVerplaatsen: 'stap_1_horeca_verplaatsen.svg',
  Stap1OnderwijsBibliotheek: 'stap_1_onderwijs_bibliotheek.svg',
  Stap1OnderwijsOpen: 'stap_1_onderwijs_open.svg',
  Stap1Theorie: 'stap_1_theorie.svg',
  Stap1Thuisbezoek: 'stap_1_thuisbezoek.svg',
  Stap1Uitvaarten: 'stap_1_uitvaarten.svg',
  Stap1WinkelsAlleen: 'stap_1_winkels_alleen.svg',
  Stap1WinkelsMarkten: 'stap_1_winkels_markten.svg',
  Stap1WinkelsOpen: 'stap_1_winkels_open.svg',
  Stopwatch: 'stopwatch.svg',
  Taxi: 'taxi.svg',
  Testbewijs: 'testbewijs.svg',
  Toegangsbewijzen: 'toegangsbewijzen.svg',
  Town: 'town.svg',
  Travel: 'travel.svg',
  Unchecked: 'unchecked.svg',
  Up: 'up.svg',
  Vaccinaties: 'vaccinaties.svg',
  Varianten: 'varianten.svg',
  Verpleeghuis: 'verpleeghuis.svg',
  VervoerEnReizenBuitenland: 'vervoer_en_reizen_buitenland.svg',
  VervoerEnReizenOv: 'vervoer_en_reizen_ov.svg',
  Vliegen: 'vliegen.svg',
  VulnerableGroups: 'vulnerable-groups.svg',
  Warn: 'warn.svg',
  Warning: 'warning.svg',
  WinkelenEnBoodschappenAlcohol: 'winkelen_en_boodschappen_alcohol.svg',
  WinkelenEnBoodschappenOpen: 'winkelen_en_boodschappen_open.svg',
  Work: 'work.svg',
  Ziekenhuis: 'ziekenhuis.svg',
  Ziektegolf: 'ziektegolf.svg',
};
