/// <reference types="react" />
import { FC, SVGAttributes } from 'react';

export interface IconProps extends SVGAttributes<SVGElement> {
  color?: string;
  size?: string | number;
}

export type Icon = FC<IconProps>;
export const AfstandSporten: Icon;
export const AlcoholVerkoop: Icon;
export const Avondklok: Icon;
export const BasisregelsAfstand: Icon;
export const BasisregelsBlijfThuis: Icon;
export const BasisregelsDrukte: Icon;
export const BasisregelsElleboog: Icon;
export const BasisregelsGeenBezoek: Icon;
export const BasisregelsHandenwassen: Icon;
export const BasisregelsMondkapje: Icon;
export const BasisregelsTesten: Icon;
export const Bezoek: Icon;
export const Bibliotheken: Icon;
export const Binnensporten: Icon;
export const Contactberoepen: Icon;
export const EenPersoonDoorgestreept: Icon;
export const FrisseLucht: Icon;
export const GedeeltelijkOpenRugzak: Icon;
export const GeenEntertainment: Icon;
export const GeenWedstrijden: Icon;
export const Groepen: Icon;
export const HorecaEnEvenementenBestellen: Icon;
export const HorecaEnEvenementenEtendrinken: Icon;
export const HorecaEnEvenementenEvenementen: Icon;
export const HorecaEvenementen: Icon;
export const Klok2100: Icon;
export const KunstcultuurMusea: Icon;
export const Lopend: Icon;
export const MaxAantalBezoekers: Icon;
export const MeerdaagseEvenementen: Icon;
export const OnderwijsEnKinderopvangKinderopvang: Icon;
export const OnderwijsEnKinderopvangNoodopvang: Icon;
export const OnderwijsEnKinderopvangOpAfstand: Icon;
export const OntmoetingenBezoek: Icon;
export const Openingstijden: Icon;
export const PubliekToegankelijkeLocaties: Icon;
export const Recreatie: Icon;
export const Reizen: Icon;
export const SportBinnensportlocaties: Icon;
export const SportBuiten: Icon;
export const SportWedstrijden: Icon;
export const SporterMetZweetband: Icon;
export const Stap1Avondklok: Icon;
export const Stap1HorecaMax: Icon;
export const Stap1HorecaPertafel: Icon;
export const Stap1HorecaReserveren: Icon;
export const Stap1HorecaSportaccomodaties: Icon;
export const Stap1HorecaTerras: Icon;
export const Stap1HorecaVerplaatsen: Icon;
export const Stap1OnderwijsBibliotheek: Icon;
export const Stap1OnderwijsOpen: Icon;
export const Stap1Theorie: Icon;
export const Stap1Thuisbezoek: Icon;
export const Stap1Uitvaarten: Icon;
export const Stap1WinkelsAlleen: Icon;
export const Stap1WinkelsMarkten: Icon;
export const Stap1WinkelsMax: Icon;
export const Stap1WinkelsOpen: Icon;
export const Testbewijs: Icon;
export const Thuis: Icon;
export const Toegangsbewijzen: Icon;
export const VervoerEnReizenBlijfthuis: Icon;
export const VervoerEnReizenBuitenland: Icon;
export const VervoerEnReizenOv: Icon;
export const WinkelenEnBoodschappenAlcohol: Icon;
export const WinkelenEnBoodschappenOpen: Icon;
