import React from 'react';
import { render } from '~/test-utils/render';

import PositiefGetesteMensen from '../../../pages/veiligheidsregio/[code]/positief-geteste-mensen';

const data = {
  last_generated: '1598883248',
  proto_name: 'VR13',
  name: 'VR13',
  code: 'VR13',
  results_per_region: {
    values: [
      {
        date_of_report_unix: 1584352800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 9,
        infected_total_counts_per_region: 4.5,
        hospital_total_counts_per_region: 0,
        infected_increase_per_region: 0.8,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1584439200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 21,
        infected_total_counts_per_region: 6.4,
        hospital_total_counts_per_region: 11,
        infected_increase_per_region: 2,
        hospital_increase_per_region: 11,
        hospital_moving_avg_per_region: 3.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1584525600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 8,
        infected_total_counts_per_region: 7.2,
        hospital_total_counts_per_region: 12,
        infected_increase_per_region: 0.7,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 4,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1584612000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 32,
        infected_total_counts_per_region: 10.2,
        hospital_total_counts_per_region: 19,
        infected_increase_per_region: 3,
        hospital_increase_per_region: 7,
        hospital_moving_avg_per_region: 6.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1584698400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 134,
        infected_total_counts_per_region: 22.7,
        hospital_total_counts_per_region: 38,
        infected_increase_per_region: 12.5,
        hospital_increase_per_region: 19,
        hospital_moving_avg_per_region: 9,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1584784800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 0,
        infected_total_counts_per_region: 19.3,
        hospital_total_counts_per_region: 51,
        infected_increase_per_region: 0,
        hospital_increase_per_region: 13,
        hospital_moving_avg_per_region: 13,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1584871200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 31,
        infected_total_counts_per_region: 22.2,
        hospital_total_counts_per_region: 58,
        infected_increase_per_region: 2.9,
        hospital_increase_per_region: 7,
        hospital_moving_avg_per_region: 13,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1584957600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 20,
        infected_total_counts_per_region: 24.1,
        hospital_total_counts_per_region: 58,
        infected_increase_per_region: 1.9,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 6.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585044000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 56,
        infected_total_counts_per_region: 29.3,
        hospital_total_counts_per_region: 76,
        infected_increase_per_region: 5.2,
        hospital_increase_per_region: 18,
        hospital_moving_avg_per_region: 8.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585130400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 53,
        infected_total_counts_per_region: 34.3,
        hospital_total_counts_per_region: 98,
        infected_increase_per_region: 5,
        hospital_increase_per_region: 22,
        hospital_moving_avg_per_region: 13.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585216800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 70,
        infected_total_counts_per_region: 40.8,
        hospital_total_counts_per_region: 102,
        infected_increase_per_region: 6.5,
        hospital_increase_per_region: 4,
        hospital_moving_avg_per_region: 14.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585303200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 75,
        infected_total_counts_per_region: 47.8,
        hospital_total_counts_per_region: 134,
        infected_increase_per_region: 7,
        hospital_increase_per_region: 32,
        hospital_moving_avg_per_region: 19.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585389600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 92,
        infected_total_counts_per_region: 56.4,
        hospital_total_counts_per_region: 163,
        infected_increase_per_region: 8.6,
        hospital_increase_per_region: 29,
        hospital_moving_avg_per_region: 21.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585476000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 70,
        infected_total_counts_per_region: 63,
        hospital_total_counts_per_region: 199,
        infected_increase_per_region: 6.5,
        hospital_increase_per_region: 36,
        hospital_moving_avg_per_region: 32.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585562400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 50,
        infected_total_counts_per_region: 67.6,
        hospital_total_counts_per_region: 223,
        infected_increase_per_region: 4.7,
        hospital_increase_per_region: 24,
        hospital_moving_avg_per_region: 29.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585648800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 56,
        infected_total_counts_per_region: 72.9,
        hospital_total_counts_per_region: 296,
        infected_increase_per_region: 5.2,
        hospital_increase_per_region: 73,
        hospital_moving_avg_per_region: 44.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585735200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 59,
        infected_total_counts_per_region: 78.4,
        hospital_total_counts_per_region: 301,
        infected_increase_per_region: 5.5,
        hospital_increase_per_region: 5,
        hospital_moving_avg_per_region: 34,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585821600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 67,
        infected_total_counts_per_region: 84.6,
        hospital_total_counts_per_region: 320,
        infected_increase_per_region: 6.3,
        hospital_increase_per_region: 19,
        hospital_moving_avg_per_region: 32.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585908000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 56,
        infected_total_counts_per_region: 89.9,
        hospital_total_counts_per_region: 347,
        infected_increase_per_region: 5.2,
        hospital_increase_per_region: 27,
        hospital_moving_avg_per_region: 17,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1585994400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 63,
        infected_total_counts_per_region: 95.7,
        hospital_total_counts_per_region: 371,
        infected_increase_per_region: 5.9,
        hospital_increase_per_region: 24,
        hospital_moving_avg_per_region: 23.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1586080800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 91,
        infected_total_counts_per_region: 104.2,
        hospital_total_counts_per_region: 388,
        infected_increase_per_region: 8.5,
        hospital_increase_per_region: 17,
        hospital_moving_avg_per_region: 22.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1586167200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 43,
        infected_total_counts_per_region: 108.3,
        hospital_total_counts_per_region: 398,
        infected_increase_per_region: 4,
        hospital_increase_per_region: 10,
        hospital_moving_avg_per_region: 17,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1586253600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 32,
        infected_total_counts_per_region: 111.3,
        hospital_total_counts_per_region: 411,
        infected_increase_per_region: 3,
        hospital_increase_per_region: 13,
        hospital_moving_avg_per_region: 13.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1586340000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 12,
        infected_total_counts_per_region: 112.4,
        hospital_total_counts_per_region: 409,
        infected_increase_per_region: 1.1,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1586426400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 69,
        infected_total_counts_per_region: 118.8,
        hospital_total_counts_per_region: 416,
        infected_increase_per_region: 6.4,
        hospital_increase_per_region: 7,
        hospital_moving_avg_per_region: 6,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1586512800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 106,
        infected_total_counts_per_region: 128.7,
        hospital_total_counts_per_region: 418,
        infected_increase_per_region: 9.9,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 2.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1586599200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 62,
        infected_total_counts_per_region: 134.5,
        hospital_total_counts_per_region: 428,
        infected_increase_per_region: 5.8,
        hospital_increase_per_region: 10,
        hospital_moving_avg_per_region: 6.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1586685600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 60,
        infected_total_counts_per_region: 140.1,
        hospital_total_counts_per_region: 430,
        infected_increase_per_region: 5.6,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 4.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1586772000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 39,
        infected_total_counts_per_region: 143.8,
        hospital_total_counts_per_region: 443,
        infected_increase_per_region: 3.6,
        hospital_increase_per_region: 13,
        hospital_moving_avg_per_region: 8.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1586858400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 52,
        infected_total_counts_per_region: 148.6,
        hospital_total_counts_per_region: 480,
        infected_increase_per_region: 4.9,
        hospital_increase_per_region: 37,
        hospital_moving_avg_per_region: 17.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1586944800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 38,
        infected_total_counts_per_region: 152.2,
        hospital_total_counts_per_region: 493,
        infected_increase_per_region: 3.5,
        hospital_increase_per_region: 13,
        hospital_moving_avg_per_region: 21,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587031200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 62,
        infected_total_counts_per_region: 157.9,
        hospital_total_counts_per_region: 522,
        infected_increase_per_region: 5.8,
        hospital_increase_per_region: 29,
        hospital_moving_avg_per_region: 26.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587117600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 102,
        infected_total_counts_per_region: 167.5,
        hospital_total_counts_per_region: 538,
        infected_increase_per_region: 9.5,
        hospital_increase_per_region: 16,
        hospital_moving_avg_per_region: 19.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587204000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 87,
        infected_total_counts_per_region: 175.6,
        hospital_total_counts_per_region: 544,
        infected_increase_per_region: 8.1,
        hospital_increase_per_region: 6,
        hospital_moving_avg_per_region: 17,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587290400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 65,
        infected_total_counts_per_region: 181.7,
        hospital_total_counts_per_region: 559,
        infected_increase_per_region: 6.1,
        hospital_increase_per_region: 15,
        hospital_moving_avg_per_region: 12.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587376800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 43,
        infected_total_counts_per_region: 185.7,
        hospital_total_counts_per_region: 573,
        infected_increase_per_region: 4,
        hospital_increase_per_region: 14,
        hospital_moving_avg_per_region: 11.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587463200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 45,
        infected_total_counts_per_region: 189.9,
        hospital_total_counts_per_region: 578,
        infected_increase_per_region: 4.2,
        hospital_increase_per_region: 5,
        hospital_moving_avg_per_region: 11.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587549600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 48,
        infected_total_counts_per_region: 194.4,
        hospital_total_counts_per_region: 595,
        infected_increase_per_region: 4.5,
        hospital_increase_per_region: 17,
        hospital_moving_avg_per_region: 12,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587636000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 66,
        infected_total_counts_per_region: 200.5,
        hospital_total_counts_per_region: 605,
        infected_increase_per_region: 6.2,
        hospital_increase_per_region: 10,
        hospital_moving_avg_per_region: 10.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587722400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 41,
        infected_total_counts_per_region: 204.4,
        hospital_total_counts_per_region: 616,
        infected_increase_per_region: 3.8,
        hospital_increase_per_region: 11,
        hospital_moving_avg_per_region: 12.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587808800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 49,
        infected_total_counts_per_region: 208.9,
        hospital_total_counts_per_region: 623,
        infected_increase_per_region: 4.6,
        hospital_increase_per_region: 7,
        hospital_moving_avg_per_region: 9.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587895200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 52,
        infected_total_counts_per_region: 213.8,
        hospital_total_counts_per_region: 630,
        infected_increase_per_region: 4.9,
        hospital_increase_per_region: 7,
        hospital_moving_avg_per_region: 8.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1587981600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 22,
        infected_total_counts_per_region: 215.9,
        hospital_total_counts_per_region: 632,
        infected_increase_per_region: 2.1,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 5.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1588068000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 16,
        infected_total_counts_per_region: 217.3,
        hospital_total_counts_per_region: 638,
        infected_increase_per_region: 1.5,
        hospital_increase_per_region: 6,
        hospital_moving_avg_per_region: 5,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1588154400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 37,
        infected_total_counts_per_region: 220.8,
        hospital_total_counts_per_region: 646,
        infected_increase_per_region: 3.5,
        hospital_increase_per_region: 8,
        hospital_moving_avg_per_region: 5.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1588240800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 33,
        infected_total_counts_per_region: 223.9,
        hospital_total_counts_per_region: 651,
        infected_increase_per_region: 3.1,
        hospital_increase_per_region: 5,
        hospital_moving_avg_per_region: 6.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1588327200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 35,
        infected_total_counts_per_region: 227.2,
        hospital_total_counts_per_region: 657,
        infected_increase_per_region: 3.3,
        hospital_increase_per_region: 6,
        hospital_moving_avg_per_region: 6.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1588413600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 41,
        infected_total_counts_per_region: 231,
        hospital_total_counts_per_region: 661,
        infected_increase_per_region: 3.8,
        hospital_increase_per_region: 4,
        hospital_moving_avg_per_region: 5,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1588500000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 16,
        infected_total_counts_per_region: 232.5,
        hospital_total_counts_per_region: 665,
        infected_increase_per_region: 1.5,
        hospital_increase_per_region: 4,
        hospital_moving_avg_per_region: 4.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1588586400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 6,
        infected_total_counts_per_region: 233.1,
        hospital_total_counts_per_region: 669,
        infected_increase_per_region: 0.6,
        hospital_increase_per_region: 4,
        hospital_moving_avg_per_region: 4,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1588672800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 44,
        infected_total_counts_per_region: 237.2,
        hospital_total_counts_per_region: 675,
        infected_increase_per_region: 4.1,
        hospital_increase_per_region: 6,
        hospital_moving_avg_per_region: 4.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1588759200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 34,
        infected_total_counts_per_region: 240.3,
        hospital_total_counts_per_region: 680,
        infected_increase_per_region: 3.2,
        hospital_increase_per_region: 5,
        hospital_moving_avg_per_region: 5,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1588845600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 37,
        infected_total_counts_per_region: 243.8,
        hospital_total_counts_per_region: 680,
        infected_increase_per_region: 3.5,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 3.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1588932000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 23,
        infected_total_counts_per_region: 245.9,
        hospital_total_counts_per_region: 685,
        infected_increase_per_region: 2.1,
        hospital_increase_per_region: 5,
        hospital_moving_avg_per_region: 3.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589018400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 15,
        infected_total_counts_per_region: 247.3,
        hospital_total_counts_per_region: 686,
        infected_increase_per_region: 1.4,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 2,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589104800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 20,
        infected_total_counts_per_region: 249.2,
        hospital_total_counts_per_region: 687,
        infected_increase_per_region: 1.9,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 2.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589191200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 23,
        infected_total_counts_per_region: 251.3,
        hospital_total_counts_per_region: 692,
        infected_increase_per_region: 2.1,
        hospital_increase_per_region: 5,
        hospital_moving_avg_per_region: 2.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589277600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 10,
        infected_total_counts_per_region: 252.3,
        hospital_total_counts_per_region: 697,
        infected_increase_per_region: 0.9,
        hospital_increase_per_region: 5,
        hospital_moving_avg_per_region: 3.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589364000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 12,
        infected_total_counts_per_region: 253.4,
        hospital_total_counts_per_region: 697,
        infected_increase_per_region: 1.1,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 3.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589450400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 28,
        infected_total_counts_per_region: 256,
        hospital_total_counts_per_region: 699,
        infected_increase_per_region: 2.6,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 2.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589536800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 15,
        infected_total_counts_per_region: 257.4,
        hospital_total_counts_per_region: 704,
        infected_increase_per_region: 1.4,
        hospital_increase_per_region: 5,
        hospital_moving_avg_per_region: 2.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589623200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 14,
        infected_total_counts_per_region: 258.7,
        hospital_total_counts_per_region: 704,
        infected_increase_per_region: 1.3,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 2.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589709600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 7,
        infected_total_counts_per_region: 259.4,
        hospital_total_counts_per_region: 706,
        infected_increase_per_region: 0.7,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 2.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589796000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 5,
        infected_total_counts_per_region: 259.9,
        hospital_total_counts_per_region: 707,
        infected_increase_per_region: 0.5,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589882400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 5,
        infected_total_counts_per_region: 260.3,
        hospital_total_counts_per_region: 711,
        infected_increase_per_region: 0.5,
        hospital_increase_per_region: 4,
        hospital_moving_avg_per_region: 2.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1589968800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 11,
        infected_total_counts_per_region: 261.4,
        hospital_total_counts_per_region: 711,
        infected_increase_per_region: 1,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 1.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1590055200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 15,
        infected_total_counts_per_region: 262.8,
        hospital_total_counts_per_region: 711,
        infected_increase_per_region: 1.4,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 1.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1590141600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 9,
        infected_total_counts_per_region: 263.6,
        hospital_total_counts_per_region: 710,
        infected_increase_per_region: 0.8,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1590228000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 10,
        infected_total_counts_per_region: 264.5,
        hospital_total_counts_per_region: 710,
        infected_increase_per_region: 0.9,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1590314400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 6,
        infected_total_counts_per_region: 265.1,
        hospital_total_counts_per_region: 712,
        infected_increase_per_region: 0.6,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1590400800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 4,
        infected_total_counts_per_region: 265.5,
        hospital_total_counts_per_region: 712,
        infected_increase_per_region: 0.4,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1590487200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 4,
        infected_total_counts_per_region: 265.8,
        hospital_total_counts_per_region: 712,
        infected_increase_per_region: 0.4,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1590573600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 7,
        infected_total_counts_per_region: 266.5,
        hospital_total_counts_per_region: 712,
        infected_increase_per_region: 0.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1590660000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 8,
        infected_total_counts_per_region: 267.2,
        hospital_total_counts_per_region: 712,
        infected_increase_per_region: 0.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1590746400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 10,
        infected_total_counts_per_region: 268.2,
        hospital_total_counts_per_region: 712,
        infected_increase_per_region: 0.9,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1590832800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 6,
        infected_total_counts_per_region: 268.7,
        hospital_total_counts_per_region: 714,
        infected_increase_per_region: 0.6,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1590919200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 9,
        infected_total_counts_per_region: 269.6,
        hospital_total_counts_per_region: 714,
        infected_increase_per_region: 0.8,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591005600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 9,
        infected_total_counts_per_region: 270.4,
        hospital_total_counts_per_region: 714,
        infected_increase_per_region: 0.8,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591092000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 1,
        infected_total_counts_per_region: 270.5,
        hospital_total_counts_per_region: 715,
        infected_increase_per_region: 0.1,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591178400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 3,
        infected_total_counts_per_region: 270.8,
        hospital_total_counts_per_region: 715,
        infected_increase_per_region: 0.3,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591264800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 0,
        infected_total_counts_per_region: 270.8,
        hospital_total_counts_per_region: 715,
        infected_increase_per_region: 0,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591351200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 0,
        infected_total_counts_per_region: 270.8,
        hospital_total_counts_per_region: 715,
        infected_increase_per_region: 0,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591437600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 0,
        infected_total_counts_per_region: 270.8,
        hospital_total_counts_per_region: 715,
        infected_increase_per_region: 0,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591524000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 75,
        infected_total_counts_per_region: 277.8,
        hospital_total_counts_per_region: 718,
        infected_increase_per_region: 7,
        hospital_increase_per_region: 3,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591610400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 22,
        infected_total_counts_per_region: 279.8,
        hospital_total_counts_per_region: 718,
        infected_increase_per_region: 2.1,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591696800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 12,
        infected_total_counts_per_region: 281,
        hospital_total_counts_per_region: 719,
        infected_increase_per_region: 1.1,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 1.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591783200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 24,
        infected_total_counts_per_region: 283.2,
        hospital_total_counts_per_region: 719,
        infected_increase_per_region: 2.2,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591869600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 22,
        infected_total_counts_per_region: 285.3,
        hospital_total_counts_per_region: 719,
        infected_increase_per_region: 2.1,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1591956000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 9,
        infected_total_counts_per_region: 286.1,
        hospital_total_counts_per_region: 720,
        infected_increase_per_region: 0.8,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592042400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 24,
        infected_total_counts_per_region: 288.3,
        hospital_total_counts_per_region: 721,
        infected_increase_per_region: 2.2,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592128800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 13,
        infected_total_counts_per_region: 289.6,
        hospital_total_counts_per_region: 721,
        infected_increase_per_region: 1.2,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592215200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 13,
        infected_total_counts_per_region: 290.8,
        hospital_total_counts_per_region: 721,
        infected_increase_per_region: 1.2,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592301600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 20,
        infected_total_counts_per_region: 292.6,
        hospital_total_counts_per_region: 721,
        infected_increase_per_region: 1.9,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592388000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 12,
        infected_total_counts_per_region: 293.8,
        hospital_total_counts_per_region: 721,
        infected_increase_per_region: 1.1,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592474400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 11,
        infected_total_counts_per_region: 294.8,
        hospital_total_counts_per_region: 723,
        infected_increase_per_region: 1,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592560800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 2,
        infected_total_counts_per_region: 295,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.2,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 1.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592647200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 8,
        infected_total_counts_per_region: 295.7,
        hospital_total_counts_per_region: 724,
        infected_increase_per_region: 0.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592733600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 7,
        infected_total_counts_per_region: 296.4,
        hospital_total_counts_per_region: 724,
        infected_increase_per_region: 0.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592820000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 7,
        infected_total_counts_per_region: 297,
        hospital_total_counts_per_region: 724,
        infected_increase_per_region: 0.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592906400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 9,
        infected_total_counts_per_region: 297.9,
        hospital_total_counts_per_region: 724,
        infected_increase_per_region: 0.8,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1592992800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 14,
        infected_total_counts_per_region: 299.2,
        hospital_total_counts_per_region: 724,
        infected_increase_per_region: 1.3,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1593079200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 6,
        infected_total_counts_per_region: 299.7,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.6,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1593165600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 10,
        infected_total_counts_per_region: 300.7,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.9,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1593252000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 7,
        infected_total_counts_per_region: 301.3,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1593338400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 3,
        infected_total_counts_per_region: 301.6,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.3,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1593424800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 8,
        infected_total_counts_per_region: 302.4,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1593511200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 4,
        infected_total_counts_per_region: 302.7,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.4,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1593597600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 4,
        infected_total_counts_per_region: 303.1,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.4,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1593684000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 5,
        infected_total_counts_per_region: 303.6,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.5,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1593770400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 10,
        infected_total_counts_per_region: 304.5,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.9,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1593856800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 8,
        infected_total_counts_per_region: 305.3,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1593943200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 6,
        infected_total_counts_per_region: 305.8,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.6,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594029600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 3,
        infected_total_counts_per_region: 306.1,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.3,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594116000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 2,
        infected_total_counts_per_region: 306.3,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.2,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594202400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 7,
        infected_total_counts_per_region: 306.9,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594288800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 3,
        infected_total_counts_per_region: 307.2,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.3,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594375200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 10,
        infected_total_counts_per_region: 308.1,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0.9,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594461600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 5,
        infected_total_counts_per_region: 308.6,
        hospital_total_counts_per_region: 726,
        infected_increase_per_region: 0.5,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594548000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 4,
        infected_total_counts_per_region: 309,
        hospital_total_counts_per_region: 726,
        infected_increase_per_region: 0.4,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594634400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 12,
        infected_total_counts_per_region: 310.1,
        hospital_total_counts_per_region: 726,
        infected_increase_per_region: 1.1,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594720800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 6,
        infected_total_counts_per_region: 310.7,
        hospital_total_counts_per_region: 726,
        infected_increase_per_region: 0.6,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594807200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 5,
        infected_total_counts_per_region: 311.1,
        hospital_total_counts_per_region: 726,
        infected_increase_per_region: 0.5,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594893600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 20,
        infected_total_counts_per_region: 313,
        hospital_total_counts_per_region: 727,
        infected_increase_per_region: 1.9,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1594980000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 17,
        infected_total_counts_per_region: 314.6,
        hospital_total_counts_per_region: 727,
        infected_increase_per_region: 1.6,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1595066400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 0,
        infected_total_counts_per_region: 314.4,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 0,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1595152800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 33,
        infected_total_counts_per_region: 317.5,
        hospital_total_counts_per_region: 725,
        infected_increase_per_region: 3.1,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1595239200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 29,
        infected_total_counts_per_region: 320.2,
        hospital_total_counts_per_region: 727,
        infected_increase_per_region: 2.7,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 0,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1595325600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 24,
        infected_total_counts_per_region: 322.4,
        hospital_total_counts_per_region: 728,
        infected_increase_per_region: 2.2,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1595412000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 18,
        infected_total_counts_per_region: 324.1,
        hospital_total_counts_per_region: 728,
        infected_increase_per_region: 1.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1595498400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 16,
        infected_total_counts_per_region: 325.6,
        hospital_total_counts_per_region: 728,
        infected_increase_per_region: 1.5,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1595584800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 20,
        infected_total_counts_per_region: 327.5,
        hospital_total_counts_per_region: 730,
        infected_increase_per_region: 1.9,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1595671200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 23,
        infected_total_counts_per_region: 329.6,
        hospital_total_counts_per_region: 731,
        infected_increase_per_region: 2.1,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1595757600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 29,
        infected_total_counts_per_region: 332.3,
        hospital_total_counts_per_region: 731,
        infected_increase_per_region: 2.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1595844000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 47,
        infected_total_counts_per_region: 336.7,
        hospital_total_counts_per_region: 731,
        infected_increase_per_region: 4.4,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1595930400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 30,
        infected_total_counts_per_region: 339.5,
        hospital_total_counts_per_region: 734,
        infected_increase_per_region: 2.8,
        hospital_increase_per_region: 3,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596016800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 31,
        infected_total_counts_per_region: 342.4,
        hospital_total_counts_per_region: 735,
        infected_increase_per_region: 2.9,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 1.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596103200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 72,
        infected_total_counts_per_region: 349.1,
        hospital_total_counts_per_region: 736,
        infected_increase_per_region: 6.7,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 1.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596189600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 53,
        infected_total_counts_per_region: 354.1,
        hospital_total_counts_per_region: 736,
        infected_increase_per_region: 5,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596276000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 67,
        infected_total_counts_per_region: 360.4,
        hospital_total_counts_per_region: 736,
        infected_increase_per_region: 6.3,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596362400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 30,
        infected_total_counts_per_region: 363.2,
        hospital_total_counts_per_region: 737,
        infected_increase_per_region: 2.8,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596448800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 50,
        infected_total_counts_per_region: 367.8,
        hospital_total_counts_per_region: 737,
        infected_increase_per_region: 4.7,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596535200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 149,
        infected_total_counts_per_region: 381.8,
        hospital_total_counts_per_region: 741,
        infected_increase_per_region: 13.9,
        hospital_increase_per_region: 4,
        hospital_moving_avg_per_region: 1.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596621600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 67,
        infected_total_counts_per_region: 388,
        hospital_total_counts_per_region: 741,
        infected_increase_per_region: 6.3,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 1.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596708000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 160,
        infected_total_counts_per_region: 402.9,
        hospital_total_counts_per_region: 740,
        infected_increase_per_region: 14.9,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596794400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 80,
        infected_total_counts_per_region: 410.4,
        hospital_total_counts_per_region: 742,
        infected_increase_per_region: 7.5,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596880800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 102,
        infected_total_counts_per_region: 419.9,
        hospital_total_counts_per_region: 744,
        infected_increase_per_region: 9.5,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1596967200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 89,
        infected_total_counts_per_region: 428.3,
        hospital_total_counts_per_region: 747,
        infected_increase_per_region: 8.3,
        hospital_increase_per_region: 3,
        hospital_moving_avg_per_region: 2.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1597053600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 194,
        infected_total_counts_per_region: 446.4,
        hospital_total_counts_per_region: 750,
        infected_increase_per_region: 18.1,
        hospital_increase_per_region: 3,
        hospital_moving_avg_per_region: 2.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1597140000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 120,
        infected_total_counts_per_region: 457.6,
        hospital_total_counts_per_region: 751,
        infected_increase_per_region: 11.2,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 2.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1597226400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 111,
        infected_total_counts_per_region: 468,
        hospital_total_counts_per_region: 752,
        infected_increase_per_region: 10.4,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 1.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1597312800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 75,
        infected_total_counts_per_region: 475,
        hospital_total_counts_per_region: 753,
        infected_increase_per_region: 7,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1597399200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 135,
        infected_total_counts_per_region: 487.6,
        hospital_total_counts_per_region: 754,
        infected_increase_per_region: 12.6,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1597485600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 142,
        infected_total_counts_per_region: 500.8,
        hospital_total_counts_per_region: 754,
        infected_increase_per_region: 13.3,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1597572000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 104,
        infected_total_counts_per_region: 510.6,
        hospital_total_counts_per_region: 755,
        infected_increase_per_region: 9.7,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1597658400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 110,
        infected_total_counts_per_region: 520.8,
        hospital_total_counts_per_region: 756,
        infected_increase_per_region: 10.3,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1597744800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 132,
        infected_total_counts_per_region: 533.2,
        hospital_total_counts_per_region: 756,
        infected_increase_per_region: 12.3,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1597831200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 100,
        infected_total_counts_per_region: 542.5,
        hospital_total_counts_per_region: 758,
        infected_increase_per_region: 9.3,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1597917600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 122,
        infected_total_counts_per_region: 553.9,
        hospital_total_counts_per_region: 759,
        infected_increase_per_region: 11.4,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1598004000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 95,
        infected_total_counts_per_region: 562.8,
        hospital_total_counts_per_region: 760,
        infected_increase_per_region: 8.9,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 1.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1598090400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 55,
        infected_total_counts_per_region: 567.9,
        hospital_total_counts_per_region: 760,
        infected_increase_per_region: 5.1,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1598176800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 81,
        infected_total_counts_per_region: 575.5,
        hospital_total_counts_per_region: 760,
        infected_increase_per_region: 7.6,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1598263200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 131,
        infected_total_counts_per_region: 587.7,
        hospital_total_counts_per_region: 761,
        infected_increase_per_region: 12.2,
        hospital_increase_per_region: 1,
        hospital_moving_avg_per_region: 0.3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1598349600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 99,
        infected_total_counts_per_region: 597,
        hospital_total_counts_per_region: 765,
        infected_increase_per_region: 9.2,
        hospital_increase_per_region: 4,
        hospital_moving_avg_per_region: 1.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1598436000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 88,
        infected_total_counts_per_region: 605.2,
        hospital_total_counts_per_region: 768,
        infected_increase_per_region: 8.2,
        hospital_increase_per_region: 3,
        hospital_moving_avg_per_region: 2.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1598522400,
        vrcode: 'VR13',
        total_reported_increase_per_region: 97,
        infected_total_counts_per_region: 614.2,
        hospital_total_counts_per_region: 770,
        infected_increase_per_region: 9.1,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 3,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1598608800,
        vrcode: 'VR13',
        total_reported_increase_per_region: 86,
        infected_total_counts_per_region: 622.3,
        hospital_total_counts_per_region: 773,
        infected_increase_per_region: 8,
        hospital_increase_per_region: 3,
        hospital_moving_avg_per_region: 2.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1598695200,
        vrcode: 'VR13',
        total_reported_increase_per_region: 73,
        infected_total_counts_per_region: 629.1,
        hospital_total_counts_per_region: 773,
        infected_increase_per_region: 6.8,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 1.7,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1598781600,
        vrcode: 'VR13',
        total_reported_increase_per_region: 64,
        infected_total_counts_per_region: 635.1,
        hospital_total_counts_per_region: 773,
        infected_increase_per_region: 6,
        hospital_increase_per_region: 0,
        hospital_moving_avg_per_region: 1,
        date_of_insertion_unix: 1598877431,
      },
      {
        date_of_report_unix: 1598868000,
        vrcode: 'VR13',
        total_reported_increase_per_region: 116,
        infected_total_counts_per_region: 645.9,
        hospital_total_counts_per_region: 775,
        infected_increase_per_region: 10.8,
        hospital_increase_per_region: 2,
        hospital_moving_avg_per_region: 0.7,
        date_of_insertion_unix: 1598877431,
      },
    ],
    last_value: {
      date_of_report_unix: 1598868000,
      vrcode: 'VR13',
      total_reported_increase_per_region: 116,
      infected_total_counts_per_region: 645.9,
      hospital_total_counts_per_region: 775,
      infected_increase_per_region: 10.8,
      hospital_increase_per_region: 2,
      hospital_moving_avg_per_region: 0.7,
      date_of_insertion_unix: 1598877431,
    },
  },
  ggd: {
    values: [
      {
        week_unix: 1595203200,
        week_start_unix: 1595203200,
        week_end_unix: 1595808000,
        vrcode: 'VR13',
        average: 434,
        date_of_insertion_unix: 1598392779,
      },
      {
        week_unix: 1595808000,
        week_start_unix: 1595808000,
        week_end_unix: 1596412800,
        vrcode: 'VR13',
        average: 1226,
        date_of_insertion_unix: 1598392779,
      },
      {
        week_unix: 1596412800,
        week_start_unix: 1596412800,
        week_end_unix: 1597017600,
        vrcode: 'VR13',
        average: 470,
        date_of_insertion_unix: 1598392779,
      },
      {
        week_unix: 1597017600,
        week_start_unix: 1597017600,
        week_end_unix: 1597622400,
        vrcode: 'VR13',
        average: 1041,
        date_of_insertion_unix: 1598392779,
      },
      {
        week_unix: 1597622400,
        week_start_unix: 1597622400,
        week_end_unix: 1598227200,
        vrcode: 'VR13',
        average: 361,
        date_of_insertion_unix: 1598392779,
      },
    ],
    last_value: {
      week_unix: 1597622400,
      week_start_unix: 1597622400,
      week_end_unix: 1598227200,
      vrcode: 'VR13',
      average: 361,
      date_of_insertion_unix: 1598392779,
    },
  },
  sewer_per_installation: {
    values: [
      {
        rwzi_awzi_code: '11014',
        values: [
          {
            date_measurement_unix: 1595289600,
            week_start_unix: 1595289600,
            week_end_unix: 1595894400,
            week: 30,
            rwzi_awzi_code: '11014',
            rwzi_awzi_name: 'Amsterdam-West',
            vrcode: 'VR13',
            vrnaam: 'Amsterdam-Amstelland',
            gmcode: 'GM0363',
            rna_normalized: 434,
            date_of_insertion_unix: 1598392779,
          },
          {
            date_measurement_unix: 1595808000,
            week_start_unix: 1595808000,
            week_end_unix: 1596412800,
            week: 31,
            rwzi_awzi_code: '11014',
            rwzi_awzi_name: 'Amsterdam-West',
            vrcode: 'VR13',
            vrnaam: 'Amsterdam-Amstelland',
            gmcode: 'GM0363',
            rna_normalized: 1226,
            date_of_insertion_unix: 1598392779,
          },
          {
            date_measurement_unix: 1596326400,
            week_start_unix: 1596326400,
            week_end_unix: 1596931200,
            week: 32,
            rwzi_awzi_code: '11014',
            rwzi_awzi_name: 'Amsterdam-West',
            vrcode: 'VR13',
            vrnaam: 'Amsterdam-Amstelland',
            gmcode: 'GM0363',
            rna_normalized: 470,
            date_of_insertion_unix: 1598392779,
          },
          {
            date_measurement_unix: 1597104000,
            week_start_unix: 1597104000,
            week_end_unix: 1597708800,
            week: 33,
            rwzi_awzi_code: '11014',
            rwzi_awzi_name: 'Amsterdam-West',
            vrcode: 'VR13',
            vrnaam: 'Amsterdam-Amstelland',
            gmcode: 'GM0363',
            rna_normalized: 1041,
            date_of_insertion_unix: 1598392779,
          },
          {
            date_measurement_unix: 1597622400,
            week_start_unix: 1597622400,
            week_end_unix: 1598227200,
            week: 34,
            rwzi_awzi_code: '11014',
            rwzi_awzi_name: 'Amsterdam-West',
            vrcode: 'VR13',
            vrnaam: 'Amsterdam-Amstelland',
            gmcode: 'GM0363',
            rna_normalized: 361,
            date_of_insertion_unix: 1598392779,
          },
        ],
        last_value: {
          date_measurement_unix: 1597622400,
          week_start_unix: 1597622400,
          week_end_unix: 1598227200,
          week: 34,
          rwzi_awzi_code: '11014',
          rwzi_awzi_name: 'Amsterdam-West',
          vrcode: 'VR13',
          vrnaam: 'Amsterdam-Amstelland',
          gmcode: 'GM0363',
          rna_normalized: 361,
          date_of_insertion_unix: 1598392779,
        },
      },
    ],
  },
};

describe('Page: PositiefGetesteMensen', () => {
  it('should use total_reported_increase_per_region for Results per Region', () => {
    const { getByText } = render(<PositiefGetesteMensen data={data} />);

    getByText('116');
  });

  it('should show a signaalwaarde', () => {
    const { getByText } = render(<PositiefGetesteMensen data={data} />);

    getByText(/signaalwaarde/i);
  });
});
