/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run 'yarn generate-data-types' to regenerate this file.
 */

export type ArchivedNlId = 'NL';

export interface ArchivedNl {
  last_generated: string;
  proto_name: ArchivedNlId;
  name: ArchivedNlId;
  code: ArchivedNlId;
  behavior_archived_20230411: NlBehavior;
  behavior_annotations_archived_20230412: NlBehaviorAnnotations;
  behavior_per_age_group_archived_20230411: NlBehaviorPerAgeGroup;
  doctor_archived_20210903: NlDoctor;
}
export interface NlBehavior {
  values: NlBehaviorValue[];
  last_value: NlBehaviorValue;
}
export interface NlBehaviorValue {
  number_of_participants: number;
  curfew_compliance?: number | null;
  curfew_compliance_trend: ('up' | 'down' | 'equal') | null;
  wash_hands_compliance?: number | null;
  wash_hands_compliance_trend: ('up' | 'down' | 'equal') | null;
  keep_distance_compliance?: number | null;
  keep_distance_compliance_trend: ('up' | 'down' | 'equal') | null;
  work_from_home_compliance?: number | null;
  work_from_home_compliance_trend: ('up' | 'down' | 'equal') | null;
  avoid_crowds_compliance?: number | null;
  avoid_crowds_compliance_trend: ('up' | 'down' | 'equal') | null;
  symptoms_stay_home_if_mandatory_compliance?: number | null;
  symptoms_stay_home_if_mandatory_compliance_trend?: ('up' | 'down' | 'equal') | null;
  symptoms_get_tested_compliance?: number | null;
  symptoms_get_tested_compliance_trend?: ('up' | 'down' | 'equal') | null;
  wear_mask_public_indoors_compliance?: number | null;
  wear_mask_public_indoors_compliance_trend: ('up' | 'down' | 'equal') | null;
  wear_mask_public_transport_compliance?: number | null;
  wear_mask_public_transport_compliance_trend?: ('up' | 'down' | 'equal') | null;
  sneeze_cough_elbow_compliance?: number | null;
  sneeze_cough_elbow_compliance_trend: ('up' | 'down' | 'equal') | null;
  max_visitors_compliance?: number | null;
  max_visitors_compliance_trend: ('up' | 'down' | 'equal') | null;
  ventilate_home_compliance?: number | null;
  ventilate_home_compliance_trend: ('up' | 'down' | 'equal') | null;
  selftest_visit_compliance?: number | null;
  selftest_visit_compliance_trend: ('up' | 'down' | 'equal') | null;
  posttest_isolation_compliance?: number | null;
  posttest_isolation_compliance_trend: ('up' | 'down' | 'equal') | null;
  curfew_support?: number | null;
  curfew_support_trend: ('up' | 'down' | 'equal') | null;
  wash_hands_support?: number | null;
  wash_hands_support_trend: ('up' | 'down' | 'equal') | null;
  keep_distance_support?: number | null;
  keep_distance_support_trend: ('up' | 'down' | 'equal') | null;
  work_from_home_support?: number | null;
  work_from_home_support_trend: ('up' | 'down' | 'equal') | null;
  avoid_crowds_support?: number | null;
  avoid_crowds_support_trend: ('up' | 'down' | 'equal') | null;
  symptoms_stay_home_if_mandatory_support?: number | null;
  symptoms_stay_home_if_mandatory_support_trend?: ('up' | 'down' | 'equal') | null;
  symptoms_get_tested_support?: number | null;
  symptoms_get_tested_support_trend?: ('up' | 'down' | 'equal') | null;
  wear_mask_public_indoors_support?: number | null;
  wear_mask_public_indoors_support_trend: ('up' | 'down' | 'equal') | null;
  wear_mask_public_transport_support?: number | null;
  wear_mask_public_transport_support_trend?: ('up' | 'down' | 'equal') | null;
  sneeze_cough_elbow_support?: number | null;
  sneeze_cough_elbow_support_trend: ('up' | 'down' | 'equal') | null;
  max_visitors_support?: number | null;
  max_visitors_support_trend: ('up' | 'down' | 'equal') | null;
  ventilate_home_support?: number | null;
  ventilate_home_support_trend: ('up' | 'down' | 'equal') | null;
  selftest_visit_support?: number | null;
  selftest_visit_support_trend: ('up' | 'down' | 'equal') | null;
  posttest_isolation_support?: number | null;
  posttest_isolation_support_trend: ('up' | 'down' | 'equal') | null;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlBehaviorAnnotations {
  values: NlBehaviorAnnotations1[];
}
export interface NlBehaviorAnnotations1 {
  behavior_indicator:
    | 'wash_hands'
    | 'curfew'
    | 'keep_distance'
    | 'work_from_home'
    | 'avoid_crowds'
    | 'symptoms_stay_home_if_mandatory'
    | 'symptoms_get_tested'
    | 'wear_mask_public_indoors'
    | 'wear_mask_public_transport'
    | 'sneeze_cough_elbow'
    | 'max_visitors'
    | 'ventilate_home'
    | 'selftest_visit'
    | 'posttest_isolation';
  message_title_nl: string;
  message_title_en: string;
  message_desc_nl: string;
  message_desc_en: string;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlBehaviorPerAgeGroup {
  keep_distance_compliance?: NlBehaviorPerAgeGroupValue;
  keep_distance_support?: NlBehaviorPerAgeGroupValue;
  sneeze_cough_elbow_compliance?: NlBehaviorPerAgeGroupValue;
  sneeze_cough_elbow_support?: NlBehaviorPerAgeGroupValue;
  wash_hands_compliance?: NlBehaviorPerAgeGroupValue;
  wash_hands_support?: NlBehaviorPerAgeGroupValue;
  work_from_home_compliance?: NlBehaviorPerAgeGroupValue;
  work_from_home_support?: NlBehaviorPerAgeGroupValue;
  ventilate_home_compliance?: NlBehaviorPerAgeGroupValue;
  ventilate_home_support?: NlBehaviorPerAgeGroupValue;
  selftest_visit_compliance?: NlBehaviorPerAgeGroupValue;
  selftest_visit_support?: NlBehaviorPerAgeGroupValue;
  posttest_isolation_compliance?: NlBehaviorPerAgeGroupValue;
  posttest_isolation_support?: NlBehaviorPerAgeGroupValue;
  date_of_insertion_unix: number;
  date_start_unix: number;
  date_end_unix: number;
}
export interface NlBehaviorPerAgeGroupValue {
  '16_24': number | null;
  '25_39': number | null;
  '40_54': number | null;
  '55_69': number | null;
  '70_plus': number | null;
}
export interface NlDoctor {
  values: NlDoctorValue[];
  last_value: NlDoctorValue;
}
export interface NlDoctorValue {
  date_start_unix: number;
  date_end_unix: number;
  covid_symptoms_per_100k: number;
  covid_symptoms: number;
  date_of_insertion_unix: number;
}

export type GmCode = string;

export interface Gm {
  last_generated: string;
  proto_name: GmCode;
  name: GmCode;
  code: GmCode;
  static_values: GmStaticValues;
  deceased_rivm_archived_20221231: GmDeceasedRivmArchived_20221231;
  difference: GmDifference;
  hospital_nice: GmHospitalNice;
  tested_overall: GmTestedOverall;
  sewer: GmSewer;
  sewer_per_installation: GmSewerPerInstallation;
  sewer_installation_measurement: GmSewerInstallationMeasurement;
  vaccine_coverage_per_age_group: GmVaccineCoveragePerAgeGroup;
  vaccine_coverage_per_age_group_archived: GmVaccineCoveragePerAgeGroupArchived;
  vaccine_coverage_per_age_group_archived_20220908: GmVaccineCoveragePerAgeGroupArchived_20220908;
  booster_coverage_archived_20220904: GmBoosterCoverageArchived_20220904;
}
export interface GmStaticValues {
  population_count: number;
  population_count_connected_to_rwzis: number;
}
export interface GmDeceasedRivmArchived_20221231 {
  values: GmDeceasedRivmArchived_20221231Value[];
  last_value: GmDeceasedRivmArchived_20221231Value;
}
export interface GmDeceasedRivmArchived_20221231Value {
  covid_daily: number;
  covid_daily_moving_average: number | null;
  covid_total: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface GmDifference {
  tested_overall__infected_per_100k_moving_average: DifferenceDecimal;
  tested_overall__infected_moving_average: DifferenceDecimal;
  hospital_nice__admissions_on_date_of_reporting_moving_average: DifferenceDecimal;
  sewer__average?: DifferenceInteger;
  deceased_rivm__covid_daily_archived_20221231: DifferenceInteger;
}
export interface DifferenceDecimal {
  old_value: number;
  difference: number;
  old_date_unix: number;
  new_date_unix: number;
}
export interface DifferenceInteger {
  old_value: number;
  difference: number;
  old_date_unix: number;
  new_date_unix: number;
}
export interface GmHospitalNice {
  values: GmHospitalNiceValue[];
  last_value: GmHospitalNiceValue;
}
export interface GmHospitalNiceValue {
  date_unix: number;
  admissions_on_date_of_admission: number;
  admissions_on_date_of_admission_moving_average: number | null;
  admissions_on_date_of_admission_moving_average_rounded: number | null;
  admissions_on_date_of_reporting: number;
  date_of_insertion_unix: number;
}
export interface GmTestedOverall {
  values: GmTestedOverallValue[];
  last_value: GmTestedOverallValue;
}
export interface GmTestedOverallValue {
  date_unix: number;
  infected: number;
  infected_moving_average: number | null;
  infected_moving_average_rounded: number | null;
  infected_per_100k: number;
  infected_per_100k_moving_average: number | null;
  date_of_insertion_unix: number;
}
export interface GmSewer {
  values: GmSewerValue[];
  last_value: GmSewerValue;
}
export interface GmSewerValue {
  date_start_unix: number;
  date_end_unix: number;
  average: number;
  date_of_insertion_unix: number;
  data_is_outdated: boolean;
}
export interface GmSewerPerInstallation {
  values: MunicipalSewerPerInstallationInstallation[];
}
export interface MunicipalSewerPerInstallationInstallation {
  rwzi_awzi_name: string;
  values: GmSewerPerInstallationValue[];
  last_value: GmSewerPerInstallationValue;
}
export interface GmSewerPerInstallationValue {
  date_unix: number;
  rna_normalized: number;
  date_of_insertion_unix: number;
}
export interface GmSewerInstallationMeasurement {
  date_start_unix: number;
  date_end_unix: number;
  total_number_of_samples: number;
  sampled_installation_count: number;
  total_installation_count: number;
  date_of_insertion_unix: number;
}
export interface GmVaccineCoveragePerAgeGroup {
  values: GmVaccineCoveragePerAgeGroupValue[];
}
export interface GmVaccineCoveragePerAgeGroupValue {
  vaccination_type: string;
  birthyear_range_12_plus: string;
  birthyear_range_18_plus: string;
  birthyear_range_60_plus: string | null;
  vaccinated_percentage_12_plus: number | null;
  vaccinated_percentage_12_plus_label: string | null;
  vaccinated_percentage_18_plus: number | null;
  vaccinated_percentage_18_plus_label: string | null;
  vaccinated_percentage_60_plus: number | null;
  vaccinated_percentage_60_plus_label: string | null;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface GmVaccineCoveragePerAgeGroupArchived {
  values: GmVaccineCoveragePerAgeGroupArchivedValue[];
}
export interface GmVaccineCoveragePerAgeGroupArchivedValue {
  age_group_range: '12+' | '18+';
  fully_vaccinated_percentage: number | null;
  has_one_shot_percentage: number | null;
  birthyear_range: string;
  fully_vaccinated_percentage_label: string | null;
  has_one_shot_percentage_label: string | null;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface GmVaccineCoveragePerAgeGroupArchived_20220908 {
  values: GmVaccineCoveragePerAgeGroupArchived_20220908Value[];
}
export interface GmVaccineCoveragePerAgeGroupArchived_20220908Value {
  age_group_range: '12+' | '18+';
  fully_vaccinated_percentage: number | null;
  booster_shot_percentage: number | null;
  has_one_shot_percentage: number | null;
  birthyear_range: string;
  fully_vaccinated_percentage_label: string | null;
  booster_shot_percentage_label: string | null;
  has_one_shot_percentage_label: string | null;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface GmBoosterCoverageArchived_20220904 {
  values: GmBoosterCoverageArchived_20220904Value[];
}
export interface GmBoosterCoverageArchived_20220904Value {
  age_group?: '12+' | '18+';
  percentage: number;
  percentage_label: string | null;
  date_unix: number;
  date_of_insertion_unix: number;
}

export type GmCollectionId = 'GM_COLLECTION';

export interface GmCollection {
  last_generated: string;
  proto_name: GmCollectionId;
  name: GmCollectionId;
  code: GmCollectionId;
  hospital_nice: GmCollectionHospitalNice[];
  hospital_nice_choropleth: GmCollectionHospitalNice[];
  tested_overall: GmCollectionTestedOverall[];
  sewer: GmCollectionSewer[];
  vaccine_coverage_per_age_group: GmCollectionVaccineCoveragePerAgeGroup[];
}
export interface GmCollectionHospitalNice {
  date_unix: number;
  gmcode: string;
  admissions_on_date_of_admission: number;
  admissions_on_date_of_admission_per_100000: number;
  admissions_on_date_of_reporting: number;
  date_of_insertion_unix: number;
}
export interface GmCollectionTestedOverall {
  date_unix: number;
  gmcode: string;
  infected_per_100k: number;
  infected: number;
  date_of_insertion_unix: number;
}
export interface GmCollectionSewer {
  date_start_unix: number;
  date_end_unix: number;
  gmcode: string;
  average: number;
  total_installation_count?: number;
  date_of_insertion_unix: number;
  data_is_outdated: boolean;
}
export interface GmCollectionVaccineCoveragePerAgeGroup {
  gmcode: string;
  vaccination_type: string;
  birthyear_range_12_plus: string;
  birthyear_range_18_plus: string;
  birthyear_range_60_plus: string | null;
  vaccinated_percentage_12_plus: number | null;
  vaccinated_percentage_12_plus_label: string | null;
  vaccinated_percentage_18_plus: number | null;
  vaccinated_percentage_18_plus_label: string | null;
  vaccinated_percentage_60_plus: number | null;
  vaccinated_percentage_60_plus_label: string | null;
  date_unix: number;
  date_of_insertion_unix: number;
}

export type NlId = 'NL';

export interface Nl {
  last_generated: string;
  proto_name: NlId;
  name: NlId;
  code: NlId;
  difference: NlDifference;
  named_difference: NlNamedDifference;
  booster_shot_administered_archived_20220904: NlBoosterShotAdministeredArchived_20220904;
  repeating_shot_administered: NlRepeatingShotAdministered;
  booster_coverage_archived_20220904: NlBoosterCoverageArchived_20220904;
  g_number: NlGNumber;
  infectious_people: NlInfectiousPeople;
  intensive_care_nice: NlIntensiveCareNice;
  intensive_care_nice_per_age_group: NlIntensiveCareNicePerAgeGroup;
  tested_overall: NlTestedOverall;
  tested_per_age_group: NlTestedPerAgeGroup;
  reproduction: NlReproduction;
  sewer: NlSewer;
  hospital_nice: NlHospitalNice;
  hospital_nice_per_age_group: NlHospitalNicePerAgeGroup;
  hospital_lcps: NlHospitalLcps;
  intensive_care_lcps: NlIntensiveCareLcps;
  tested_ggd: NlTestedGgd;
  tested_ggd_archived: NlTestedGgdArchived;
  nursing_home_archived_20230126: NlNursingHomeArchived_20230126;
  vulnerable_nursing_home: NlVulnerableNursingHome;
  vulnerable_tested_per_age_group: NlVulnerableTestedPerAgeGroup;
  vulnerable_hospital_admissions: NlVulnerableHospitalAdmissions;
  disability_care_archived_20230126: NlDisabilityCareArchived_20230126;
  deceased_rivm_archived_20221231: NlDeceasedRivmArchived_20221231;
  deceased_rivm_per_age_group_archived_20221231: NlDeceasedRivmPerAgeGroupArchived_20221231;
  deceased_cbs: NlDeceasedCbs;
  elderly_at_home_archived_20230126: NlElderlyAtHomeArchived_20230126;
  vaccine_vaccinated_or_support: NlVaccineVaccinatedOrSupport;
  corona_melder_app_download: NlCoronaMelderAppDownload;
  corona_melder_app_warning: NlCoronaMelderAppWarning;
  vaccine_coverage?: NlVaccineCoverage;
  vaccine_delivery_estimate: NlVaccineDeliveryEstimate;
  vaccine_delivery_per_supplier: NlVaccineDeliveryPerSupplier;
  vaccine_administered: NlVaccineAdministered;
  vaccine_administered_doctors: NlVaccineAdministeredDoctors;
  vaccine_administered_ggd_ghor: NlVaccineAdministeredGgdGhor;
  vaccine_administered_ggd: NlVaccineAdministeredGgd;
  vaccine_administered_hospitals_and_care_institutions: NlVaccineAdministeredHospitalsAndCareInstitutions;
  vaccine_administered_total: NlVaccineAdministeredTotal;
  vaccine_administered_planned: NlVaccineAdministeredPlanned;
  vaccine_administered_last_timeframe: NlVaccineAdministeredLastTimeframe;
  vaccine_campaigns: NlVaccineCampaigns;
  vaccine_campaigns_archived_20220908: NlVaccineCampaignsArchived_20220908;
  vaccine_planned_archived_20220908: NlVaccinePlannedArchived_20220908;
  vaccine_coverage_per_age_group: NlVaccineCoveragePerAgeGroup;
  vaccine_coverage_per_age_group_archived: NlVaccineCoveragePerAgeGroupArchived;
  vaccine_coverage_per_age_group_archived_20220908: NlVaccineCoveragePerAgeGroupArchived_20220908;
  vaccine_coverage_per_age_group_estimated_fully_vaccinated: NlVaccineCoveragePerAgeGroupEstimatedFullyVaccinatedValue;
  vaccine_coverage_per_age_group_estimated_autumn_2022: NlVaccineCoveragePerAgeGroupEstimatedAutumn_2022Value;
  vaccine_coverage_per_age_group_estimated_archived_20220908: NlVaccineCoveragePerAgeGroupEstimatedArchived_20220908Value;
  vaccine_stock: NlVaccineStock;
  variants?: NlVariants;
  self_test_overall: NlSelfTestOverall;
}
export interface NlDifference {
  tested_overall__infected_per_100k_moving_average: DifferenceDecimal;
  tested_overall__infected_moving_average: DifferenceDecimal;
  tested_ggd__tested_total_moving_average: DifferenceDecimal;
  tested_ggd__infected_percentage_moving_average: DifferenceDecimal;
  infectious_people__estimate: DifferenceInteger;
  hospital_nice__admissions_on_date_of_reporting_moving_average: DifferenceDecimal;
  hospital_lcps__beds_occupied_covid: DifferenceInteger;
  intensive_care_nice__admissions_on_date_of_reporting_moving_average: DifferenceDecimal;
  intensive_care_lcps__beds_occupied_covid: DifferenceInteger;
  sewer__average: DifferenceInteger;
  vulnerable_nursing_home__infected_locations_total: DifferenceInteger;
  nursing_home__newly_infected_people_archived_20230126: DifferenceInteger;
  nursing_home__deceased_daily_archived_20230126: DifferenceInteger;
  vulnerable_tested_per_age_group: DifferenceInteger;
  vulnerable_hospital_admissions: DifferenceInteger;
  reproduction__index_average: DifferenceDecimal;
  deceased_rivm__covid_daily_archived_20221231: DifferenceInteger;
}
export interface DifferenceDecimal {
  old_value: number;
  difference: number;
  old_date_unix: number;
  new_date_unix: number;
}
export interface DifferenceInteger {
  old_value: number;
  difference: number;
  old_date_unix: number;
  new_date_unix: number;
}
export interface NlNamedDifference {
  variants__percentage: NamedDifferenceDecimal[];
}
export interface NamedDifferenceDecimal {
  variant_code: string;
  old_value: number;
  difference: number;
  old_date_unix: number;
  new_date_unix: number;
}
export interface NlBoosterShotAdministeredArchived_20220904 {
  values: NlBoosterShotAdministeredArchived_20220904Value[];
  last_value: NlBoosterShotAdministeredArchived_20220904Value;
}
export interface NlBoosterShotAdministeredArchived_20220904Value {
  administered_total: number;
  ggd_administered_total: number;
  others_administered_total: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlRepeatingShotAdministered {
  values: NlRepeatingShotAdministeredValue[];
  last_value: NlRepeatingShotAdministeredValue;
}
export interface NlRepeatingShotAdministeredValue {
  ggd_administered_total: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlBoosterCoverageArchived_20220904 {
  values: NlBoosterCoverageArchived_20220904Value[];
}
export interface NlBoosterCoverageArchived_20220904Value {
  age_group?: '12+' | '18+';
  percentage: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlGNumber {
  values: NlGNumberValue[];
  last_value: NlGNumberValue;
}
export interface NlGNumberValue {
  g_number: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlInfectiousPeople {
  values: NlInfectiousPeopleValue[];
  last_value: NlInfectiousPeopleValue;
}
export interface NlInfectiousPeopleValue {
  margin_low: number;
  estimate: number | null;
  margin_high: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlIntensiveCareNice {
  values: NlIntensiveCareNiceValue[];
  last_value: NlIntensiveCareNiceValue;
}
export interface NlIntensiveCareNiceValue {
  admissions_on_date_of_admission: number;
  admissions_on_date_of_admission_moving_average: number | null;
  admissions_on_date_of_admission_moving_average_rounded: number | null;
  admissions_on_date_of_reporting: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlIntensiveCareNicePerAgeGroup {
  values: NlIntensiveCareNicePerAgeGroupValue[];
  last_value: NlIntensiveCareNicePerAgeGroupValue;
}
export interface NlIntensiveCareNicePerAgeGroupValue {
  admissions_age_0_19_per_million: number;
  admissions_age_20_29_per_million: number;
  admissions_age_30_39_per_million: number;
  admissions_age_40_49_per_million: number;
  admissions_age_50_59_per_million: number;
  admissions_age_60_69_per_million: number;
  admissions_age_70_79_per_million: number;
  admissions_age_80_89_per_million: number;
  admissions_age_90_plus_per_million: number;
  admissions_overall_per_million: number;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlTestedOverall {
  values: NlTestedOverallValue[];
  last_value: NlTestedOverallValue;
}
export interface NlTestedOverallValue {
  infected: number;
  infected_moving_average: number | null;
  infected_moving_average_rounded: number | null;
  infected_per_100k: number;
  infected_per_100k_moving_average: number | null;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlTestedPerAgeGroup {
  values: NlTestedPerAgeGroupValue[];
  last_value: NlTestedPerAgeGroupValue;
}
export interface NlTestedPerAgeGroupValue {
  infected_age_0_9_per_100k: number;
  infected_age_10_19_per_100k: number;
  infected_age_20_29_per_100k: number;
  infected_age_30_39_per_100k: number;
  infected_age_40_49_per_100k: number;
  infected_age_50_59_per_100k: number;
  infected_age_60_69_per_100k: number;
  infected_age_70_79_per_100k: number;
  infected_age_80_89_per_100k: number;
  infected_age_90_plus_per_100k: number;
  infected_overall_per_100k: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlReproduction {
  values: NlReproductionValue[];
  last_value: NlReproductionValue;
}
export interface NlReproductionValue {
  index_low: number | null;
  index_average: number | null;
  index_high: number | null;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlSewer {
  values: NlSewerValue[];
  last_value: NlSewerValue;
}
export interface NlSewerValue {
  average: number | null;
  date_of_insertion_unix: number;
  date_unix: number;
}
export interface NlHospitalNice {
  values: NlHospitalNiceValue[];
  last_value: NlHospitalNiceValue;
}
export interface NlHospitalNiceValue {
  admissions_on_date_of_admission: number;
  admissions_on_date_of_admission_moving_average: number | null;
  admissions_on_date_of_admission_moving_average_rounded: number | null;
  admissions_on_date_of_reporting: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlHospitalNicePerAgeGroup {
  values: NlHospitalNicePerAgeGroupValue[];
  last_value: NlHospitalNicePerAgeGroupValue;
}
export interface NlHospitalNicePerAgeGroupValue {
  admissions_age_0_19_per_million: number;
  admissions_age_20_29_per_million: number;
  admissions_age_30_39_per_million: number;
  admissions_age_40_49_per_million: number;
  admissions_age_50_59_per_million: number;
  admissions_age_60_69_per_million: number;
  admissions_age_70_79_per_million: number;
  admissions_age_80_89_per_million: number;
  admissions_age_90_plus_per_million: number;
  admissions_overall_per_million: number;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlHospitalLcps {
  values: NlHospitalLcpsValue[];
  last_value: NlHospitalLcpsValue;
}
export interface NlHospitalLcpsValue {
  beds_occupied_covid: number | null;
  influx_covid_patients: number | null;
  influx_covid_patients_moving_average: number | null;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlIntensiveCareLcps {
  values: NlIntensiveCareLcpsValue[];
  last_value: NlIntensiveCareLcpsValue;
}
export interface NlIntensiveCareLcpsValue {
  beds_occupied_covid: number | null;
  beds_occupied_covid_percentage: number | null;
  influx_covid_patients: number | null;
  influx_covid_patients_moving_average: number | null;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlTestedGgd {
  values: NlTestedGgdValue[];
  last_value: NlTestedGgdValue;
}
export interface NlTestedGgdValue {
  infected: number;
  infected_moving_average: number | null;
  infected_percentage: number;
  infected_percentage_moving_average: number | null;
  tested_total: number;
  tested_total_moving_average: number | null;
  tested_total_moving_average_rounded: number | null;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlTestedGgdArchived {
  values: NlTestedGgdArchivedValue[];
  last_value: NlTestedGgdArchivedValue;
}
export interface NlTestedGgdArchivedValue {
  infected_percentage: number;
  infected_percentage_moving_average: number | null;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlNursingHomeArchived_20230126 {
  values: NlNursingHomeArchived_20230126Value[];
  last_value: NlNursingHomeArchived_20230126Value;
}
export interface NlNursingHomeArchived_20230126Value {
  newly_infected_people: number;
  newly_infected_people_moving_average: number | null;
  deceased_daily: number;
  deceased_daily_moving_average: number | null;
  newly_infected_locations: number;
  infected_locations_total: number;
  infected_locations_percentage: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVulnerableNursingHome {
  values: NlVulnerableNursingHomeValue[];
  last_value: NlVulnerableNursingHomeValue;
}
export interface NlVulnerableNursingHomeValue {
  newly_infected_locations: number;
  infected_locations_total: number;
  infected_locations_percentage: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVulnerableTestedPerAgeGroup {
  infected_age_70_plus: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVulnerableHospitalAdmissions {
  admissions_age_70_plus: number;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlDisabilityCareArchived_20230126 {
  values: NlDisabilityCareArchived_20230126Value[];
  last_value: NlDisabilityCareArchived_20230126Value;
}
export interface NlDisabilityCareArchived_20230126Value {
  newly_infected_people: number;
  newly_infected_people_moving_average: number | null;
  deceased_daily: number;
  deceased_daily_moving_average: number | null;
  newly_infected_locations: number;
  infected_locations_total: number;
  infected_locations_percentage: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlDeceasedRivmArchived_20221231 {
  values: NlDeceasedRivmArchived_20221231Value[];
  last_value: NlDeceasedRivmArchived_20221231Value;
}
export interface NlDeceasedRivmArchived_20221231Value {
  covid_daily: number;
  covid_daily_moving_average: number | null;
  covid_total: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlDeceasedRivmPerAgeGroupArchived_20221231 {
  values: NlDeceasedRivmPerAgeGroupArchived_20221231Value[];
}
export interface NlDeceasedRivmPerAgeGroupArchived_20221231Value {
  age_group_range: string;
  age_group_percentage: number;
  covid_percentage: number;
  date_unix?: number;
  date_of_insertion_unix: number;
}
export interface NlDeceasedCbs {
  values: NlDeceasedCbsValue[];
  last_value: NlDeceasedCbsValue;
}
export interface NlDeceasedCbsValue {
  registered: number;
  expected: number;
  expected_min: number;
  expected_max: number;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlElderlyAtHomeArchived_20230126 {
  values: NlElderlyAtHomeArchived_20230126Value[];
  last_value: NlElderlyAtHomeArchived_20230126Value;
}
export interface NlElderlyAtHomeArchived_20230126Value {
  positive_tested_daily: number;
  positive_tested_daily_moving_average: number | null;
  positive_tested_daily_per_100k: number;
  deceased_daily: number;
  deceased_daily_moving_average: number | null;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineVaccinatedOrSupport {
  values: NlVaccineVaccinatedOrSupportValue[];
  last_value: NlVaccineVaccinatedOrSupportValue;
}
export interface NlVaccineVaccinatedOrSupportValue {
  percentage_average: number;
  percentage_70_plus: number | null;
  percentage_55_69: number | null;
  percentage_40_54: number | null;
  percentage_25_39: number | null;
  percentage_16_24: number | null;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlCoronaMelderAppDownload {
  values: NlCoronaMelderAppDownloadValue[];
  last_value: NlCoronaMelderAppDownloadValue;
}
export interface NlCoronaMelderAppDownloadValue {
  count: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlCoronaMelderAppWarning {
  values: NlCoronaMelderAppWarningValue[];
  last_value: NlCoronaMelderAppWarningValue;
}
export interface NlCoronaMelderAppWarningValue {
  count: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineCoverage {
  values: NlVaccineCoverageValue[];
  last_value: NlVaccineCoverageValue;
}
export interface NlVaccineCoverageValue {
  booster_vaccinated: number;
  partially_vaccinated: number;
  fully_vaccinated: number;
  partially_or_fully_vaccinated: number;
  date_start_unix: number;
  date_end_unix: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineDeliveryEstimate {
  values: NlVaccineDeliveryEstimateValue[];
  last_value: NlVaccineDeliveryEstimateValue;
}
export interface NlVaccineDeliveryEstimateValue {
  total: number;
  date_of_insertion_unix: number;
  date_start_unix: number;
  date_end_unix: number;
}
export interface NlVaccineDeliveryPerSupplier {
  values: NlVaccineDeliveryPerSupplierValue[];
  last_value: NlVaccineDeliveryPerSupplierValue;
}
export interface NlVaccineDeliveryPerSupplierValue {
  total: number;
  bio_n_tech_pfizer: number;
  moderna: number;
  astra_zeneca: number;
  cure_vac?: number;
  janssen?: number;
  sanofi?: number;
  is_estimate: boolean;
  week_number: number;
  date_of_insertion_unix: number;
  date_start_unix: number;
  date_end_unix: number;
  date_of_report_unix: number;
}
export interface NlVaccineAdministered {
  values: NlVaccineAdministeredValue[];
  last_value: NlVaccineAdministeredValue;
}
export interface NlVaccineAdministeredValue {
  pfizer: number;
  moderna: number;
  astra_zeneca: number;
  cure_vac?: number;
  janssen?: number;
  sanofi?: number;
  novavax: number;
  total: number;
  date_of_insertion_unix: number;
  date_start_unix: number;
  date_end_unix: number;
}
export interface NlVaccineAdministeredDoctors {
  values: NlVaccineAdministeredDoctorsValue[];
  last_value: NlVaccineAdministeredDoctorsValue;
}
export interface NlVaccineAdministeredDoctorsValue {
  estimated: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineAdministeredGgdGhor {
  values: NlVaccineAdministeredGgdGhorValue[];
  last_value: NlVaccineAdministeredGgdGhorValue;
}
export interface NlVaccineAdministeredGgdGhorValue {
  reported: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineAdministeredGgd {
  values: NlVaccineAdministeredGgdValue[];
  last_value: NlVaccineAdministeredGgdValue;
}
export interface NlVaccineAdministeredGgdValue {
  estimated: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineAdministeredHospitalsAndCareInstitutions {
  values: NlVaccineAdministeredHospitalsAndCareInstitutionsValue[];
  last_value: NlVaccineAdministeredHospitalsAndCareInstitutionsValue;
}
export interface NlVaccineAdministeredHospitalsAndCareInstitutionsValue {
  estimated: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineAdministeredTotal {
  values: NlVaccineAdministeredTotalValue[];
  last_value: NlVaccineAdministeredTotalValue;
}
export interface NlVaccineAdministeredTotalValue {
  estimated: number;
  reported: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineAdministeredPlanned {
  values: NlVaccineAdministeredPlannedValue[];
  last_value: NlVaccineAdministeredPlannedValue;
}
export interface NlVaccineAdministeredPlannedValue {
  doses: number;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineAdministeredLastTimeframe {
  vaccine_types: NlVaccineType[];
  date_unix: number;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineType {
  vaccine_type_name: string;
  vaccine_type_value: number;
}
export interface NlVaccineCampaigns {
  vaccine_campaigns: NlVaccineCampaign[];
  date_unix: number;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineCampaign {
  vaccine_campaign_order: number;
  vaccine_campaign_name_nl: string;
  vaccine_campaign_name_en: string;
  vaccine_administered_total: number;
  vaccine_administered_last_timeframe: number;
}
export interface NlVaccineCampaignsArchived_20220908 {
  vaccine_campaigns: NlVaccineCampaignsArchived_202209081[];
  date_unix: number;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineCampaignsArchived_202209081 {
  vaccine_campaign_order: number;
  vaccine_campaign_name_nl: string;
  vaccine_campaign_name_en: string;
  vaccine_administered_total: number;
  vaccine_administered_last_week: number;
}
export interface NlVaccinePlannedArchived_20220908 {
  doses: number;
  date_unix: number;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineCoveragePerAgeGroup {
  values: NlVaccineCoveragePerAgeGroupValue[];
}
export interface NlVaccineCoveragePerAgeGroupValue {
  age_group_range: '5-11' | '12-17' | '18-29' | '30-39' | '40-49' | '50-59' | '60-69' | '70-79' | '80+';
  age_group_percentage: number;
  age_group_total: number;
  autumn_2022_vaccinated: number | null;
  fully_vaccinated: number;
  autumn_2022_vaccinated_percentage: number | null;
  fully_vaccinated_percentage: number;
  date_unix: number;
  date_of_insertion_unix: number;
  date_of_report_unix: number;
  birthyear_range: string;
}
export interface NlVaccineCoveragePerAgeGroupArchived {
  values: NlVaccineCoveragePerAgeGroupArchivedValue[];
}
export interface NlVaccineCoveragePerAgeGroupArchivedValue {
  age_group_range: '5-11' | '12-17' | '18-30' | '31-40' | '41-50' | '51-60' | '61-70' | '71-80' | '81+';
  age_group_percentage: number;
  age_group_total: number;
  fully_vaccinated: number;
  has_one_shot: number;
  fully_vaccinated_percentage: number;
  has_one_shot_percentage: number;
  date_unix: number;
  date_of_insertion_unix: number;
  date_of_report_unix: number;
  birthyear_range: string;
}
export interface NlVaccineCoveragePerAgeGroupArchived_20220908 {
  values: NlVaccineCoveragePerAgeGroupArchived_20220908Value[];
}
export interface NlVaccineCoveragePerAgeGroupArchived_20220908Value {
  age_group_range: '5-11' | '12-17' | '18-29' | '30-39' | '40-49' | '50-59' | '60-69' | '70-79' | '80+';
  age_group_percentage: number;
  age_group_total: number;
  fully_vaccinated: number;
  booster_shot: number | null;
  has_one_shot: number | null;
  fully_vaccinated_percentage: number;
  booster_shot_percentage: number | null;
  has_one_shot_percentage: number | null;
  date_unix: number;
  date_of_insertion_unix: number;
  date_of_report_unix: number;
  birthyear_range: string;
}
export interface NlVaccineCoveragePerAgeGroupEstimatedFullyVaccinatedValue {
  values: NlVaccineCoveragePerAgeGroupEstimatedFullyVaccinated[];
  last_value: NlVaccineCoveragePerAgeGroupEstimatedFullyVaccinated;
}
export interface NlVaccineCoveragePerAgeGroupEstimatedFullyVaccinated {
  age_12_plus_birthyear: string;
  age_12_plus_vaccinated: number;
  age_18_plus_birthyear: string;
  age_18_plus_vaccinated: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineCoveragePerAgeGroupEstimatedAutumn_2022Value {
  values: NlVaccineCoveragePerAgeGroupEstimatedAutumn_2022[];
  last_value: NlVaccineCoveragePerAgeGroupEstimatedAutumn_2022;
}
export interface NlVaccineCoveragePerAgeGroupEstimatedAutumn_2022 {
  age_12_plus_birthyear: string;
  age_12_plus_vaccinated: number;
  age_60_plus_birthyear: string;
  age_60_plus_vaccinated: number;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineCoveragePerAgeGroupEstimatedArchived_20220908Value {
  values: NlVaccineCoveragePerAgeGroupEstimatedArchived_20220908[];
  last_value: NlVaccineCoveragePerAgeGroupEstimatedArchived_20220908;
}
export interface NlVaccineCoveragePerAgeGroupEstimatedArchived_20220908 {
  age_18_plus_fully_vaccinated: number;
  age_18_plus_has_one_shot: number;
  age_18_plus_birthyear: string;
  age_12_plus_fully_vaccinated: number;
  age_12_plus_has_one_shot: number;
  age_12_plus_birthyear: string;
  date_unix: number;
  date_of_insertion_unix: number;
}
export interface NlVaccineStock {
  values: NlVaccineStockValue[];
  last_value: NlVaccineStockValue;
}
export interface NlVaccineStockValue {
  total_available: number | null;
  total_not_available: number | null;
  bio_n_tech_pfizer_available: number | null;
  bio_n_tech_pfizer_not_available: number | null;
  bio_n_tech_pfizer_total: number | null;
  moderna_available: number | null;
  moderna_not_available: number | null;
  moderna_total: number | null;
  astra_zeneca_available: number | null;
  astra_zeneca_not_available: number | null;
  astra_zeneca_total: number | null;
  janssen_available: number | null;
  janssen_not_available: number | null;
  janssen_total: number | null;
  date_of_insertion_unix: number;
  date_unix: number;
}
export interface NlVariants {
  values: NlVariantsVariant[];
}
export interface NlVariantsVariant {
  variant_code: string;
  values: NlVariantsVariantValue[];
  last_value: NlVariantsVariantValue;
}
export interface NlVariantsVariantValue {
  order: number;
  occurrence: number;
  percentage: number;
  is_variant_of_concern: boolean;
  has_historical_significance: boolean;
  sample_size: number;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
  date_of_report_unix: number;
  label_nl: string;
  label_en: string;
}
export interface NlSelfTestOverall {
  values: NlSelfTestOverallValue[];
  last_value: NlSelfTestOverallValue;
}
export interface NlSelfTestOverallValue {
  infected_percentage: number | null;
  date_start_unix: number;
  date_end_unix: number;
  date_of_insertion_unix: number;
}

export type VrCollectionId = 'VR_COLLECTION';

export interface VrCollection {
  last_generated: string;
  proto_name: VrCollectionId;
  name: VrCollectionId;
  code: VrCollectionId;
  disability_care_archived_20230126: VrCollectionDisabilityCareArchived_20230126[];
  elderly_at_home_archived_20230126: VrCollectionElderlyAtHomeArchived_20230126[];
  vulnerable_nursing_home: VrCollectionVulnerableNursingHome[];
}
export interface VrCollectionDisabilityCareArchived_20230126 {
  newly_infected_people: number;
  newly_infected_locations: number;
  infected_locations_total: number;
  infected_locations_percentage: number;
  deceased_daily: number;
  date_unix: number;
  date_of_insertion_unix: number;
  vrcode: string;
}
export interface VrCollectionElderlyAtHomeArchived_20230126 {
  positive_tested_daily: number;
  positive_tested_daily_per_100k: number;
  deceased_daily: number;
  date_unix: number;
  date_of_insertion_unix: number;
  vrcode: string;
}
export interface VrCollectionVulnerableNursingHome {
  newly_infected_locations: number;
  infected_locations_total: number;
  infected_locations_percentage: number;
  date_of_insertion_unix: number;
  date_unix: number;
  vrcode: string;
}
