name: Deploy Preview

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop
      - master

jobs:
  build_and_deploy_job:
    if: (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')) && startsWith(github.head_ref, 'lokalise-') == false
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

      - name: Push POST request
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ secrets.TRIGGER_BRANCH_DEPLOY }}
          data: '{"branchName": "${{ steps.extract_branch.outputs.branch }}"'

  # close_pull_request_job:
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed'
  #   runs-on: ubuntu-latest
  #   name: Close Pull Request Job
  #   steps:
  #     - name: Close Pull Request
  #       id: closepullrequest
  #       uses: Azure/static-web-apps-deploy@v0.0.1-preview
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_RIVER_0AFDB141E }}
  #         action: 'close'
