name: CI-dev
on:
  push:
    branches:
      - develop

jobs:
  trigger-develop-build:
    environment: Development
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/${{ secrets.AZURE_ORGANIZATION_NAME }}/${{ secrets.AZURE_PROJECT_NAME }}
          azure-pipeline-name: ${{ secrets.AZURE_PIPELINE_NAME }}
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
