name: Lokalise

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'test' && exit 0
  merge-me:
    name: Merge me!
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


