name: Synchronize Sanity Lokalize

on:
  push:
    branches:
      - develop

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      # The bahmutov/npm-install uses caching, so by running it already in the
      # init task, the other tasks running in parallel should install quickly.
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

  sync-after-feature:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build common module
        run: yarn workspace @corona-dashboard/common build
      - name: Synchronize texts
        run: yarn workspace @corona-dashboard/cms lokalize:sync-after-feature
        with:
          sanity_token: ${{ github.sanity_token }}
