name: Synchronize Sanity Lokalize

on:
  push:
    branches:
      - develop

jobs:
  sync-after-feature:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Lookup cached node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn install

      - name: Build common module
        run: yarn workspace @corona-dashboard/common build
      - name: Synchronize texts
        run: yarn workspace @corona-dashboard/cms lokalize:sync-after-feature
        env:
          SANITY_TOKEN: ${{ secrets.sanity_token }}
      - name: Export production texts
        run: yarn workspace @corona-dashboard/cms lokalize:export --dataset=production --clean-json
      - name: Compile all code with production texts
        run: yarn workspace @corona-dashboard/app compile
